name: CDKTF OUTPUTS
on: [push]
jobs:
    preparations-job:
        runs-on: ubuntu-latest
        name: Runner setup
        steps:
            - name: Checkout the code to runner
              uses: actions/checkout@v3
            - name: Generate multiline output
              id: string
              run: |
                EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
                echo "STRING=$(curl https://time.mk)<< $EOF" >> "GITHUB_OUTPUT"
                echo "$EOF" >> "GITHUB_OUTPUT"
            - name: Comment the tf plan on the PR
              uses: actions/github-script@0.9.0
              env:
                OUTPUT: ${{steps.string.outputs.STRING}}
              with:
                github-token: ${{ github.token }} # Create a secret with a GitHub token that can comment on PRs
                script: |
                    echo $OUTPUT
