name: CDKTF PREPS
on:
    push:
        branches: 
            - main
jobs:
    preparations-job:
        runs-on: ubuntu-latest
        name: Runner setup
        steps:
            - name: Checkout the code to runner
              uses: actions/checkout@v3
            - name: Install python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11.3
            - name: Install requirements
              run: |
                  pip3 install -r requirements.txt
              shell: bash
            - name: Install from Pipfile
              run: pipenv install
              shell: bash
            - name: Install terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.4.5
            - name: Install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Generate bindings
              run: cdktf get