name: CDKTF OUTPUTS
on: [push]
jobs:
    preparations-job:
        runs-on: ubuntu-latest
        name: Runner setup
        steps:
            - name: Checkout the code to runner
              uses: actions/checkout@v3
            # - name: Generate multiline output
            #   id: string
            #   run: |
            #     EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            #     echo "STRING=$(curl https://time.mk)<< $EOF" >> "GITHUB_OUTPUT"
            #     echo "$EOF" >> "GITHUB_OUTPUT"
            # - name: Generate multiline output
            #   id: string
            #   env: 
            #     time: $(curl https://time.mk)
            #   run: |
            #     EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            #     echo "$time<<$EOF" >> "$GITHUB_OUTPUT"   
            #     echo "$EOF" >> "$GITHUB_OUTPUT"       
            # - name: Comment the tf plan on the PR
            #   uses: actions/github-script@0.9.0
            #   id: hello
            # #   env:
            # #     OUTPUT: "${{steps.string.outputs.time}}"
            #   with:
            #     github-token: ${{ github.token }} # Create a secret with a GitHub token that can comment on PRs
            #     # script: |
            #     #     return process.env.OUTPUT
            #     script:
            #         return "hello world"
            # - name: Get the result
            #   run: |
            #     echo "${{steps.hello.outputs.result}}"
            #     echo "${{steps.string.outputs.time}}"
            - name: Set multiline
              id: multi
              run: |
                EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
                CURL="uu demek ova kje raboti"
                echo "$CURL << $EOF" >> "$GITHUB_OUTPUT"
                echo "$EOF" >> "$GITHUB_OUTPUT"
            - name: Get curl
              run: echo "The selected curl is ${{ steps.multi.outputs }}"
    
