name: Printing out stuff
on: [push]
jobs:
    outputs:
        runs-on: ubuntu-latest
        steps:
            - name: Print github stuff
              run: |
                echo ${{github.repository}}/MAIN
                echo $GITHUB.WORKSPACE